from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field

class ApiError(BaseModel):
    code: str = Field(..., description="Short machine-readable error code")
    message: str = Field(..., description="Human-readable error message")


class StartSessionRequest(BaseModel):
    project_name: str = Field(..., min_length=1, description="Name of the Dalux project")
    category: Literal["tasks", "files"] = Field(default="tasks", description="Task category (e.g., 'tasks', 'files')")

class StartSessionResponse(BaseModel):
    session_id: str = Field(..., description="Unique session ID (UUID)")
    start_time: str = Field(..., description="Session start timestamp")
    end_time: str = Field(..., description="Session end timestamp")
    project_name: str = Field(..., description="Name of the Dalux project")
    category: str = Field(..., description="Task category")
    subject: str = Field(..., description="Session subject or topic")


class SendPromptRequest(BaseModel):
    # session_id: str = Field(..., description="Session ID (UUID)")
    text: str = Field(..., min_length=1, description="User prompt text")
    # Timestamp for requests is generated by the server in API layer, not sent by the client.

class SendPromptResponse(BaseModel):
    session_id: str = Field(..., description="Session ID (UUID)")
    timestamp: str = Field(..., description="Response timestamp")
    model: str = Field(..., description="Model that generated the response")
    text: str = Field(..., description="Response text")
